# Set by github - do not change.
safe: true
lsi: false
highlighter: rouge

exclude:
- bower.json
- bower_components
- Gemfile
- Gemfile.lock

title: AcePictureBot
description: >
  AcePictureBot is a open source weeb bot.
baseurl: "http://ace3df.github.io/AcePictureBot"
url: "http://ace3df.github.io/AcePictureBot"
twitter_username: ace3df
github_username:  ace3df

markdown: kramdown

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

jekyll-mentions:
  base_url: https://twitter.com

navigation:
  - pages:
    - title: Home
      path: index.md
    - path: commands.md
    - path: faq.md
  - title: Development
    pages:
    - path: donate.md
    - title: Source Code
      url: https://github.com/ace3df/AcePictureBot
      icon: code
    - title: Issues
      url: https://github.com/ace3df/AcePictureBot/issues
      icon: bug_report
  - title: Twitter Accounts
    pages:
    - title: Ace3DF (Developer)
      url: https://twitter.com/Ace3DF
      icon: perm_identity
    - title: AcePictureBot
      url: https://twitter.com/AcePictureBot
      icon: perm_contact_calendar
    - title: AceStatusBot
      url: https://twitter.com/AceStatusBot
      icon: perm_contact_calendar
    - title: AceCatgirlBot
      url: https://twitter.com/AceCatgirlBot
      icon: perm_contact_calendar
    - title: AceAnimatedBot
      url: https://twitter.com/AceAnimatedBot
      icon: perm_contact_calendar
    - title: AceYuriBot
      url: https://twitter.com/ACeYuriBot
      icon: perm_contact_calendar
    - title: AceYaoiBot
      url: https://twitter.com/AceYaoiBot
      icon: perm_contact_calendar
    - title: AceAsianBot
      url: https://twitter.com/AceAsianBot
      icon: perm_contact_calendar
