Hiei (Kantai Collection)(x)Kongou (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Akagi (Kantai Collection)(x)Graf ZeppElin (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Satsuki (Kantai Collection)(x)Minazuki (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Atago (Kantai Collection)(x)Takao (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Hamakaze (Kantai Collection)(x)Isokaze (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Amagi (Kantai Collection)(x)Unryuu (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Akashi (Kantai Collection)(x)Ooyodo (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Shigure (Kantai Collection)(x)Yuudachi (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Souryuu (Kantai Collection)(x)Graf ZeppElin (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Bismarck (Kantai Collection)(x)Graf ZeppElin (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Akigumo (Kantai Collection)(x)Yuugumo (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Amatsukaze (Kantai Collection)(x)Shimakaze (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Musashi (Kantai Collection)(x)Yamato (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Nagato (Kantai Collection)(x)Mutsu (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection
Kitakami (Kantai Collection)(x)Ooi (Kantai Collection):
  lists:
    - shipgirl
    - yuri
  series: Kantai Collection

Ayase Eli(x)Sonoda Umi:
  lists:
    - idol
    - yuri
  series: Love Live!
Ayase Eli(x)Toujou Nozomi:
  lists:
    - idol
    - yuri
  series: Love Live!
Sonoda Umi(x)Nishikino Maki:
  lists:
    - idol
    - yuri
  series: Love Live!
Yazawa Nico(x)Nishikino Maki:
  lists:
    - idol
    - yuri
  series: Love Live!
Hoshizora Rin(x)Koizumi Hanayo:
  lists:
    - idol
    - yuri
  series: Love Live!
Kousaka Honoka(x)Sonoda Umi:
  lists:
    - idol
    - yuri
  series: Love Live!

Tsushima Yoshiko(x)Sakurauchi_Riko:
  lists:
    - idol
    - yuri
  series: Love Live! Sunshine!!
Takami Chika(x)Watanabe You:
  lists:
    - idol
    - yuri
  series: Love Live! Sunshine!!

Megurine Luka(x)Hatsune Miku:
  lists:
    - vocaloid
    - yuri
  series: Vocaloid

Houraisan Kaguya(x)Fujiwara no Mokou:
  lists:
    - touhou
    - yuri
  series: Touhou
Kochiya Sanae(x)Hakurei Reimu:
  lists:
    - touhou
    - yuri
  series: Touhou

Oomuro Sakurako(x)Furutani Himawari:
  lists:
    - yuri
  series: Yuru Yuri
Kay (Girls und Panzer)(x)Darjeeling:
  lists:
    - yuri
  series: Girls und Panzer
Mercy (overwatch)(x)Pharah (overwatch):
  lists:
    - yuri
  series: Overwatch
D.va (overwatch)(x)Tracer (overwatch):
  lists:
    - yuri
  series: Overwatch
Ichinose Haru(x)Azuma Tokaku:
  lists:
    - yuri
  series: Akuma no Riddle