Hiei (Kantai Collection)(x)Kongou (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Akagi (Kantai Collection)(x)Graf ZeppElin (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Satsuki (Kantai Collection)(x)Minazuki (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Atago (Kantai Collection)(x)Takao (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Hamakaze (Kantai Collection)(x)Isokaze (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Amagi (Kantai Collection)(x)Unryuu (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Akashi (Kantai Collection)(x)Ooyodo (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Shigure (Kantai Collection)(x)Yuudachi (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Souryuu (Kantai Collection)(x)Graf ZeppElin (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Bismarck (Kantai Collection)(x)Graf ZeppElin (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Akigumo (Kantai Collection)(x)Yuugumo (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Amatsukaze (Kantai Collection)(x)Shimakaze (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Musashi (Kantai Collection)(x)Yamato (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection
Kitakami (Kantai Collection)(x)Ooi (Kantai Collection):
  lists:
    - shipgirl
  series: Kantai Collection

Ayase Eli(x)Sonoda Umi:
  lists:
    - idol
  series: Love Live!
Ayase Eli(x)Toujou Nozomi:
  lists:
    - idol
  series: Love Live!
Sonoda Umi(x)Nishikino Maki:
  lists:
    - idol
  series: Love Live!
Yazawa Nico(x)Nishikino Maki:
  lists:
    - idol
  series: Love Live!
Hoshizora Rin(x)Koizumi Hanayo:
  lists:
    - idol
  series: Love Live!
